### ISSUE TITLE
试用了一下，发现几个问题

### ISSUE THREAD

**Issue by Naivetesun** [jacobsun/edidor#1]
很喜欢这个主题，简单试用了一下。发现如下问题

- 很多代码不高亮，比如Python、asm....

- 代码首行有自动缩进
![图片](https://user-images.githubusercontent.com/23723304/57690253-d0541a00-7673-11e9-88f0-072a9d4884ff.png)

- 字体很小，右边栏很小，左边栏也偏小，而且行高很高，Categories、tag 下右边字体也很小，单行代码更小

![图片](https://user-images.githubusercontent.com/23723304/57690687-c848aa00-7674-11e9-90ce-45691e4e94f7.png)

**Comment by jacobsun** [comment]
主题还在优化中, 刚刚推送了巨量更新, 请更新看看是否还有以上问题.

**Comment by Naivetesun** [comment]
![图片](https://user-images.githubusercontent.com/23723304/57748436-879c6f80-770c-11e9-9972-68a478ad027e.png)
代码首行还是有缩进

**Comment by Naivetesun** [comment]
不对齐 强迫症有点难受

**Comment by jacobsun** [comment]
主题正式release 第一个版本. 全面重写, 此issue关闭, 有问题有请开新的.
